import React from 'react';
import { Button, Flex, Textarea } from '@chakra-ui/react';
import { useTranslation } from '@fedimint/utils';

const tos = `BY GENERATING A PRIVATE KEY FOR THIS FEDIMINT, YOU AGREE TO SERVE AS A GUARDIAN FOR THE FEDERATION. IN YOUR ROLE AS A GUARDIAN, YOU ARE SOLELY RESPONSIBLE FOR: (1) ADMINISTERING THE PILOT FEDERATION; (2) ASSESSING APPLICABLE LAWS THAT CUSTODY AND TRANSFER OF BITCOIN MAY TRIGGER IN THE RELEVANT JURISDICTIONS; (3) ENSURING THAT THIRD PARTIES WILL USE THE FEDIMINT PROTOCOL IN COMPLIANCE WITH APPLICABLE LAWS AND WILL NOT UTILIZE THE FEDIMINT PROTOCOL IN WAYS THAT HARM OR DEFRAUD USERS; AND (4) PREVENTING USE OR ADDITION OF ANY CAPABILITIES ON THE FEDIMINT PROTOCOL IN EXCESS OF THOSE PROVIDED BY FEDI, INC. YOU ACKNOWLEDGE THAT FEDI, INC. IS NOT A PARTY TO THE PILOT FEDERATION, AND IS NOT RESPONSIBLE FOR ANY OF THE FOREGOING, AND CANNOT BE HELD LIABLE FOR ANY RESULTING LOSSES, DAMAGES, OBLIGATIONS, LIABILITIES, COSTS OR DEBT, AND EXPENSES (INCLUDING BUT NOT LIMITED TO ATTORNEYS’ FEES).`;

interface Props {
  next(): void;
}

export const TermsOfService: React.FC<Props> = ({ next }) => {
  const { t } = useTranslation();
  return (
    <Flex direction='column' gap={4} maxWidth={660}>
      <Textarea value={tos} rows={14} readOnly />
      <Button onClick={next}>{t('terms-of-service.agree-and-continue')}</Button>
    </Flex>
  );
};
